version : '3.7'
services:
  mysqldb:
    image: mysql:8.4.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
